# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-09 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_team_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.BooleanField(default=False),
        ),
    ]
