# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-09 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_team_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.CharField(max_length=2000),
        ),
    ]
