# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-09 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170509_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.TextField(null=True),
        ),
    ]
